{{- if .Values.hpa.enabled }}
{{- range .Values.hpa.targets }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ . }}
  namespace: {{ include "ai-tos.namespace" $ }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ . }}
  minReplicas: 2
  maxReplicas: {{ $.Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.hpa.cpuUtilization }}
---
{{- end }}
{{- end }}
